version: "3"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/contact-keeper
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    ports:
      - "27017:27017"
